# Site settings
title: MOUZ WTF?!
tag_text: mouz wtf?!
description: Mouz changed their Logo
url: "https://mouz.wtf"
baseurl: "https://mouz.wtf"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
